spring.session.redis.namespace=zerotrust:session
app.security.login-success-uri=${LOGIN_SUCCESS_URI:/}
app.security.logout-success-path=${LOGOUT_SUCCESS_PATH:/}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${REDIS_SSL_ENABLED:true}

server.servlet.session.cookie.name=__Host-session
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.path=/
