package com.zerotrust.risk.domain;

public enum RiskReason {
    PRIORITY_SECURITY_RULE,
    BLOCKED_IP_ADDRESS,
    DEVICE_IDENTIFIER_MISSING,
    DEVICE_HISTORY_UNAVAILABLE,
    NETWORK_INTELLIGENCE_UNAVAILABLE,
    TEMPORAL_PROFILE_UNAVAILABLE,
    AUTHENTICATION_HISTORY_UNAVAILABLE,
    DEVICE_RISK,
    NETWORK_RISK,
    TEMPORAL_RISK,
    AUTHENTICATION_HISTORY_RISK
}
