package com.zerotrust.keycloak.risk.dto;

public enum RiskReason {
    PRIORITY_SECURITY_RULE,
    BLOCKED_IP_ADDRESS,
    DEVICE_IDENTIFIER_MISSING,
    NEW_DEVICE,
    PENDING_DEVICE,
    REVOKED_DEVICE,
    NETWORK_INTELLIGENCE_UNAVAILABLE,
    TEMPORAL_PROFILE_COLD_START,
    TEMPORAL_PROFILE_UNAVAILABLE,
    AUTHENTICATION_HISTORY_UNAVAILABLE,
    EXCESSIVE_AUTHENTICATION_FAILURES,
    DEVICE_RISK,
    NETWORK_RISK,
    TEMPORAL_RISK,
    AUTHENTICATION_HISTORY_RISK
}
